spring:
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

rate:
  limiter:
    capacity: 10
    refill-rate: 2

logging:
  level:
    root: INFO
    com.ratelimiter: DEBUG 